name: build
on:
  push:
    branches:  ["**"]
    tags-ignore:  ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
  
env:
  RUNTIME_VERSION: 21

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup / checkout repository
        uses: actions/checkout@v4
      - name: setup / validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup / jdk ${{ env.RUNTIME_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.RUNTIME_VERSION }}
      - name: setup / gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ !(startsWith(github.ref, 'refs/heads/mc/') || github.ref == 'refs/heads/master') || github.event_name == 'pull_request' }}
      - name: run gradle build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
